### ISSUE TITLE
CloudStor has been recently decommissioned

### ISSUE THREAD

**Issue by AlbertoJaenal** [gmberton/datasets_vg#9] opened 2024-01-19 14:50 UTC
Hello!

Thanks for this repo, is really helpful. However, I was looking into downloading Nordlandsbanen and it seems to have been decommissioned...
"CloudStor was decommissioned on December 15th, 2023. For more information, please visit https://support.aarnet.edu.au/hc/en-us/sections/6547442372367"

Do you have any alternative?
Regards

**Comment by gmberton** [comment] 2024-03-31 05:09
Hi, you can download the Nordland dataset from [here](https://drive.google.com/drive/folders/1UWdNkUtNV4pGcNnbrhU3xQAHsYP3TK5Z).
I haven't been able to automatize the download and format due to an issue of gdown when downloading large files, so you need to download summer and winter splits of Nordland from browser and then adapt the script. I will fix the script once the issue is fixed on gdown

**Comment by oravus** [comment] 2024-04-24 05:25
If you are looking for that CloudStor hosted version of Nordland, it's here [now](https://universityofadelaide.app.box.com/s/zkfk1akpbo5318fzqmtvlpp7030ex4up). For download commands, please see https://github.com/AnyLoc/AnyLoc/issues/30#issuecomment-2074038275.

**Closed as completed** 2024-04-24 14:30 UTC
