### ISSUE TITLE
nordland download url is out of date

### ISSUE THREAD

**Issue by BanaBear** [gmberton/datasets_vg#11] opened 2024-03-29 09:15 UTC
hello, i found that the url is out of date in download_nordland.py
and i can't find the cleanImageNames.txt, could you fix this problem? thanks!!

util1.download_heavy_file("https://cloudstor.aarnet.edu.au/plus/s/8L7loyTZjK0FsWT/download?path=%2F&files=summer.tar.gz",
                          join(raw_data_folder, "summer.tar.gz"))
util1.download_heavy_file("https://cloudstor.aarnet.edu.au/plus/s/8L7loyTZjK0FsWT/download?path=%2F&files=winter.tar.gz",
                          join(raw_data_folder, "winter.tar.gz"))
util1.download_heavy_file("https://cloudstor.aarnet.edu.au/plus/s/8L7loyTZjK0FsWT/download?path=%2F&files=cleanImageNames.txt&downloadStartSecret=crd03ou9qji",
                          join(raw_data_folder, "cleanImageNames.txt"))

**Comment by gmberton** [comment] 2024-03-31 05:09
Hi, you can download the Nordland dataset from [here](https://drive.google.com/drive/folders/1UWdNkUtNV4pGcNnbrhU3xQAHsYP3TK5Z).
I haven't been able to automatize the download and format due to an issue of gdown when downloading large files, so you need to download summer and winter splits of Nordland from browser and then adapt the script. I will fix the script once the issue is fixed on gdown

**Comment by Fragmentszz** [comment] 2024-04-21 06:53
but still I can't find where to get ```cleanImageNames.txt```
:(

**Comment by Fragmentszz** [comment] 2024-04-21 12:26
oh, may the files can be download from [here](https://universityofadelaide.app.box.com/s/zkfk1akpbo5318fzqmtvlpp7030ex4up)

**Comment by oravus** [comment] 2024-04-24 05:24
If you are looking for that CloudStor hosted version of Nordland, it's here [now](https://universityofadelaide.app.box.com/s/zkfk1akpbo5318fzqmtvlpp7030ex4up). For download commands, please see [this](https://github.com/AnyLoc/AnyLoc/issues/30#issuecomment-2074038275).

**Comment by gmberton** [comment] 2024-04-24 18:15
Hi @oravus, thank you for your help. I tried to fix the download script using the links you provided, but the `winter.tar.gz` seems corrupted. I tried multiple times to download it and extract with multiple libraries, but I'm getting an error and only 8970 out of 35768 are downloaded. For example, when extracting with `tar -xvzf  winter.tar.gz` I get this error (after thousands of images are correctly extracted):
```
winter/images-34312.png
winter/images-34373.png
winter/images-34381.png
tar: Skipping to next header

gzip: stdin: invalid compressed data--format violated
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
The summer tar is fine. Could you have a look at the uploaded winter tar?

**Comment by oravus** [comment] 2024-04-25 02:29
I think I have encountered this extraction issue before. Probably ideal to reupload the winter tar, will message here once that's done.

**Comment by oravus** [comment] 2024-05-11 12:37
@gmberton, Winter (and Spring) tars are now updated, thanks to @Ahmedest61.
We have tested it at our end for download/extraction. It would be great if you can also test your script.

Also, to test if the downloaded file is correct, you can run
`sha256sum winter.tar.gz`
It should return `c95a1cf99ef2cdcf9e1d9b47de1d8248a194a6c8deeb976edd099562ab20e1c2`

**Comment by gmberton** [comment] 2024-05-22 22:26
Thank you @oravus , the links work well now :)

**Closed as completed by gmberton** 2024-05-22 22:26 UTC
